export const getInvoices = () => [];
export const getSettings = () => ({});
export const saveSettings = (s: any) => {};
export const getDashboardStats = () => ({ total: 0, paid: 0, pending: 0, overdue: 0, clients: 0 });
export const getInvoices = () => [];
export const getClients = () => [];
export const saveInvoice = (inv: any) => inv;
export const saveClient = (client: any) => client;
export const markInvoicePaid = (id: string) => {};
export const deleteInvoice = (id: string) => {};
export const syncInvoicesToServer = (invs: any[]) => Promise.resolve();
