[build]
  base = "Remindrr/"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

[build.system]
  usePnpm = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200