[build]
  command = "npm install && npm run build && cp public/_redirects dist/"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  GMAIL_CLIENT_ID = "YOUR_CLIENT_ID.apps.googleusercontent.com"
  GMAIL_CLIENT_SECRET = "YOUR_CLIENT_SECRET"