[build]
  command = "npm install && npm run build && cp public/_redirects dist/"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[context.production]
  environment = { SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "***" }